name: Docker build samba image

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
          
      - name: Check Out Repo dperson/samba
        uses: actions/checkout@v2
        with:
          repository: "dperson/samba"
          ref: 'master'
          path: 'samba-git'

      - name: Get latest commit hash
        id: get-latest-commit
        run: |
          cd samba-git && echo "::set-output name=commit::$(git describe --tags `git rev-list --tags --max-count=1`)"
        shell: bash

      - uses: actions/cache@v2
        id: cache
        with:
          path: samba
          key: ${{ runner.os }}-v2-${{ steps.get-latest-commit.outputs.commit }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          platforms: all

      - name: Login to Quay.io
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set up Docker Buildx
        if: steps.cache.outputs.cache-hit != 'true'
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Override samba file
        if: steps.cache.outputs.cache-hit != 'true'
        run: cp samba/samba.sh samba-git/samba.sh

      - name: Set up build timestamp
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo "timestamp=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Build and push docker image
        if: steps.cache.outputs.cache-hit != 'true'
        id: docker_build_new
        uses: docker/build-push-action@v2
        with:
          context: ./samba-git
          file: ./samba-git/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          tags: quay.io/unixfox/samba:latest, quay.io/unixfox/samba:build-${{ env.timestamp }}