name: Docker build huginn image

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get latest commit hash
        id: get-latest-commit
        run: |
          echo "::set-output name=commit::$(git ls-remote git://github.com/huginn/huginn.git | head -n1 | awk '{print $1;}')"
        shell: bash

      - uses: actions/cache@v2
        id: cache
        with:
          path: keel
          key: ${{ runner.os }}-v1-${{ steps.get-latest-commit.outputs.commit }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          platforms: all

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Check Out Repo huginn/huginn
        uses: actions/checkout@v2
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          repository: "huginn/huginn"
          ref: 'master'
          path: 'huginn-git'
          
      - name: Login to Quay.io
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set up Docker Buildx
        if: steps.cache.outputs.cache-hit != 'true'
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Set up build timestamp
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo "timestamp=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Override prepare script
        id: override-prepare-script
        run: |
          cp huginn/scripts/prepare huginn-git/docker/scripts/prepare
        shell: bash

      - name: Downgrade libv8
        id: downgrade-libv8
        run: |
          sed -i 's/7.3.492.27.1/6.3.292.48.1/g' ./huginn-git/Gemfile.lock
          sed -i 's/0.2.9/0.2.4/g' ./huginn-git/Gemfile.lock
          sed -i 's/6.9.411/6.3/g' ./huginn-git/Gemfile.lock
        shell: bash

      - name: Build and push docker image single process
        if: steps.cache.outputs.cache-hit != 'true'
        id: docker_build_new_single_process
        uses: docker/build-push-action@v2
        with:
          context: ./huginn-git
          file: ./huginn/single-process/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: quay.io/unixfox/huginn-single-process:latest, quay.io/unixfox/huginn-single-process:build-${{ env.timestamp }}

      - name: Build and push docker image multiple processes
        if: steps.cache.outputs.cache-hit != 'true'
        id: docker_build_new_multiple_processes
        uses: docker/build-push-action@v2
        with:
          context: ./huginn-git
          file: ./huginn/multi-process/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: quay.io/unixfox/huginn-multi-process:latest, quay.io/unixfox/huginn-multi-process:build-${{ env.timestamp }}