name: Docker build nitter image

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:      
      - name: Get latest commit hash
        id: get-latest-commit
        run: |
          echo "::set-output name=commit::$(git ls-remote https://github.com/zedeus/nitter.git | head -n1 | awk '{print $1;}')"
        shell: bash

      - uses: actions/cache@v2
        id: cache
        with:
          path: nitter
          key: ${{ runner.os }}-v8-${{ steps.get-latest-commit.outputs.commit }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          platforms: all

      - name: Check Out Repo
        uses: actions/checkout@v2
          
      - name: Check Out Repo goodtiding5/docker-nitter
        uses: actions/checkout@v2
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          repository: "goodtiding5/docker-nitter"
          ref: 'master'
          path: 'nitter-git'
      
      - name: Login to Quay.io
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set up Docker Buildx
        if: steps.cache.outputs.cache-hit != 'true'
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Set up build timestamp
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo "timestamp=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Build and push docker image custom
        if: steps.cache.outputs.cache-hit != 'true'
        id: docker_build_new_custom
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./nitter/Dockerfile.custom
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          tags: quay.io/unixfox/nitter-custom:latest, quay.io/unixfox/nitter-custom:build-${{ env.timestamp }}

      - name: Build and push docker image
        if: steps.cache.outputs.cache-hit != 'true'
        id: docker_build_new
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./nitter/Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          tags: quay.io/unixfox/nitter:latest, quay.io/unixfox/nitter:build-${{ env.timestamp }}
